name: flutstrap
description: A Flutter UI library inspired by Bootstrap with responsive layouts and prebuilt components.
version: 0.0.2
homepage: https://github.com/Broadmaker/FlutStrap
repository: https://github.com/Broadmaker/FlutStrap
issue_tracker: https://github.com/Broadmaker/FlutStrap/issues
documentation: https://github.com/Broadmaker/FlutStrap#readme
license: MIT


environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Example folder (recommended for pub.dev)
  #assets:
  #  - assets/

  # Optional: fonts (only if you add custom fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

# Pub.dev topics for discoverability
# Should be lowercase and relevant to the package
topics:
  - ui
  - flutter
  - responsive
  - components
  - bootstrap